services:
  web:
    build: .
    ports:
      - "5005:5000"  # Updated port mapping
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development  # Example environment variable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 3
